### ISSUE TITLE
fix timezones

### ISSUE THREAD

**Issue by LGD-Fr** [rezometz/django-paiji2-comic#1]
for NASA APOD and Garfield

**Comment by LGD-Fr** [comment]
maybe UTC ?

**Comment by LGD-Fr** [comment]
An american timezone I suppose…

**Comment by ghost** [comment]
Damn these great Overlords...

2015-09-10 12:07 GMT+02:00 Louis-Guillaume Dubois notifications@github.com
:

**Comment by LGD-Fr** [comment]
For the time being I’ve chosen New York. I will try Adak later :-)
